USE [master]
GO

/****** Object:  Database [IEL]    Script Date: 08/05/2024 14:26:11 ******/
CREATE DATABASE [IEL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IEL', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\IEL.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'IEL_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\IEL_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IEL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [IEL] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [IEL] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [IEL] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [IEL] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [IEL] SET ARITHABORT OFF 
GO

ALTER DATABASE [IEL] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [IEL] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [IEL] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [IEL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [IEL] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [IEL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [IEL] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [IEL] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [IEL] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [IEL] SET  DISABLE_BROKER 
GO

ALTER DATABASE [IEL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [IEL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [IEL] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [IEL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [IEL] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [IEL] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [IEL] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [IEL] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [IEL] SET  MULTI_USER 
GO

ALTER DATABASE [IEL] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [IEL] SET DB_CHAINING OFF 
GO

ALTER DATABASE [IEL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [IEL] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [IEL] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [IEL] SET QUERY_STORE = OFF
GO

USE [IEL]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [IEL] SET  READ_WRITE 
GO

